# Generated by Django 5.0.2 on 2024-02-12 08:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('origin', '0003_alter_company_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='salesprocess',
            name='product_status',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='origin.productstatus'),
        ),
        migrations.AddField(
            model_name='salesprocess',
            name='sales_representative',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='salesperformance',
            name='closed_deals_count',
            field=models.IntegerField(default=0),
        ),
    ]
