# Generated by Django 5.0.2 on 2024-02-12 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('origin', '0005_remove_salesprocess_product_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesperformance',
            name='closed_deals_count',
            field=models.IntegerField(default=0),
        ),
    ]
