# Generated by Django 5.0.2 on 2024-02-13 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('origin', '0006_alter_salesperformance_closed_deals_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesperformance',
            name='month',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='salesperformance',
            name='year',
            field=models.IntegerField(default=0),
        ),
    ]
