# Generated by Django 5.0.2 on 2024-02-13 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('origin', '0007_alter_salesperformance_month_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesperformance',
            name='month',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='salesperformance',
            name='year',
            field=models.IntegerField(),
        ),
    ]
