# Generated by Django 5.0.2 on 2024-02-14 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('origin', '0009_alter_productinterest_average_interest'),
    ]

    operations = [
        migrations.AddField(
            model_name='productinterest',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
