# Generated by Django 5.0.2 on 2024-02-15 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('origin', '0011_userwithcompanycount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesprocess',
            name='date_created',
            field=models.DateField(auto_now_add=True),
        ),
    ]
