# Generated by Django 5.0.2 on 2024-02-15 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('origin', '0012_alter_salesprocess_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productstatus',
            name='date_updated',
            field=models.DateField(auto_now=True),
        ),
    ]
