# Generated by Django 5.0.2 on 2024-02-19 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('origin', '0013_alter_productstatus_date_updated'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['product_name']},
        ),
        migrations.AlterModelOptions(
            name='productstatus',
            options={'ordering': ['date_updated']},
        ),
        migrations.AlterModelOptions(
            name='salesprocess',
            options={'ordering': ['date_created']},
        ),
    ]
