# Generated by Django 5.0.2 on 2024-02-19 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('origin', '0015_alter_product_options_alter_productstatus_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ['company_name']},
        ),
    ]
