# Generated by Django 5.0.2 on 2024-02-19 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('origin', '0016_alter_company_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={},
        ),
        migrations.AlterModelOptions(
            name='productstatus',
            options={},
        ),
        migrations.AlterModelOptions(
            name='salesprocess',
            options={},
        ),
    ]
