# Generated by Django 5.0.2 on 2024-02-19 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('origin', '0017_alter_company_options_alter_product_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productstatus',
            options={'ordering': ('-date_updated',)},
        ),
    ]
