# Generated by Django 5.0.2 on 2024-02-19 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('origin', '0018_alter_productstatus_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productstatus',
            options={'ordering': ['-date_updated']},
        ),
    ]
