# Generated by Django 5.0.2 on 2024-02-19 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('origin', '0020_alter_salesprocess_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productstatus',
            options={'ordering': ['date_updated']},
        ),
    ]
