# Generated by Django 5.0.2 on 2024-02-19 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('origin', '0021_alter_productstatus_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
