# Generated by Django 5.0.2 on 2024-02-19 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('origin', '0022_company_date_created'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': (['-date_created'],)},
        ),
    ]
